version: '3'

services:
  redis:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes: 
      - ./docker/db/data:/data
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    restart: unless-stopped
    ports:
      - 3001:3001
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - WAIT_HOSTS=redis:6379
      - WAIT_HOSTS_TIMEOUT=300  
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    networks:
      - app-network
    volumes: 
      - ./server:/usr/src/app/server
      - /usr/src/app/node_modules

  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      - api
    links:
      - api
    networks:
      - app-network
    volumes: 
      - ./src:/usr/src/app/src
    environment:
      - WAIT_HOSTS=api:3001
      - WAIT_HOSTS_TIMEOUT=300  
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

networks:
  app-network:
    driver: bridge

volumes:
  data:
  node_modules: